[window]
startup_mode="Maximized"
title="Alacritty"

[shell]
program="/opt/homebrew/bin/tmux"

[font]
normal = { family = "SauceCodePro NFM", style = "Regular" }
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 18  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true
